fixtures:
  repositories:
    apt: 'https://github.com/puppetlabs/puppetlabs-apt.git'
    stdlib: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
    epel: 'https://github.com/stahnma/puppet-module-epel.git'
    augeasproviders_sysctl: 'https://github.com/hercules-team/augeasproviders_sysctl.git'
    augeasproviders_core: 'https://github.com/hercules-team/augeasproviders_core.git'
    augeas_core:
      repo: "https://github.com/puppetlabs/puppetlabs-augeas_core"
      puppet_version: ">= 6.0.0"
    yumrepo_core:
      repo: "https://github.com/puppetlabs/puppetlabs-yumrepo_core"
      puppet_version: ">= 6.0.0"
    systemd:
      repo: 'https://github.com/camptocamp/puppet-systemd.git'
      puppet_version: "< 6.1.0"
