---
Gemfile:
  optional:
    ':test':
      - gem: 'redis'
      - gem: 'mock_redis'
spec/spec_helper.rb:
  facterdb_string_keys: true

.github/workflows/ci.yml:
  with:
    beaker_hypervisor: 'docker'
    unit_runs_on: 'cern-self-hosted'
